import type { Metadata } from 'next'
import { Libre_Bodoni } from 'next/font/google'
import './globals.css'

const libre = Libre_Bodoni({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Boundless Courage LLC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${libre.className} bg-purple text-dark-armor`}>{children}</body>
    </html>
  )
}
